stages:
  super_resolution:
    cmd: python aerialimagesdetection/inference/super_resolution.py
    deps:
    - data/raw_data
    outs:
    - data/upscaled_data/
  object_detection:
    cmd: python aerialimagesdetection/inference/detection.py
    deps:
      - data/raw_data
    outs:
      - data/output/objects.csv
      - data/output/annotated_images
  building_footprint:
    cmd: python aerialimagesdetection/inference/footprint.py
    deps:
      - data/raw_data
    outs:
      - data/output/footprints.csv
      - data/output/masked_images
