stages:
  data_preparation:
    cmd: python aerialimagesdetection/training/data_preparation.py
    deps:
      - data/xView/xView_train.geojson
      - data/xView/images
    outs:
      - data/xView/labels
  tiling:
    cmd : python aerialimagesdetection/training/tiling.py
    deps:
      - data/xView/images
      - data/xView/labels
    outs:
      - data/xView/tiled
  object_detection_training:
    cmd: python aerialimagesdetection/training/detection.py
    deps:
      - data/xView/xView.yaml
      - data/xView/tiled
    params:
      - train
    outs:
      - YOLOv8/detection_model/weights/best.pt
  preprocessing:
    cmd: python aerialimagesdetection/inference/data_preprocessing.py
    deps:
    - data/raw_data
    outs:
    - data/processed_data
  object_detection:
    cmd: python aerialimagesdetection/inference/detection.py
    deps:
      - data/raw_data
      - data/processed_data
      - YOLOv8/detection_model/weights/best.pt
    outs:
      - data/output/objects.csv
      - data/output/annotated_images
  footprint:
    cmd: python aerialimagesdetection/inference/footprint.py
    deps:
      - data/processed_data
      - data/output/objects.csv
    params:
      - objects_name
    outs:
      - data/output/masked_images
